# Generated by Django 5.2.17 on 2026-08-20 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Cabang')),
                ('code', models.CharField(help_text='Contoh: JKT-01, BDG-02', max_length=20, unique=True, verbose_name='Kode Cabang')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telepon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_managed', to=settings.AUTH_USER_MODEL, verbose_name='Manager Cabang')),
            ],
            options={
                'verbose_name': 'Cabang',
                'verbose_name_plural': 'Cabang',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Auto-generate, contoh: CMP-00001', max_length=20, unique=True, verbose_name='Kode Komplain')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nama Pelanggan')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='No. HP / WhatsApp')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('table_number', models.CharField(blank=True, max_length=20, verbose_name='Nomor Meja')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Kunjungan')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='Nomor Pesanan/Struk')),
                ('category', models.CharField(choices=[('makanan', 'Kualitas Makanan'), ('pelayanan', 'Pelayanan Staff'), ('kebersihan', 'Kebersihan'), ('kecepatan', 'Kecepatan Penyajian'), ('fasilitas', 'Fasilitas / Kenyamanan'), ('pembayaran', 'Pembayaran / Struk'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('severity', models.CharField(choices=[('kritis', 'Kritis'), ('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], default='sedang', max_length=10, verbose_name='Tingkat Keparahan')),
                ('description', models.TextField(verbose_name='Deskripsi Komplain')),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='complaint_photos/%Y/%m/', verbose_name='Foto Bukti')),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('ditinjau', 'Sedang Ditinjau'), ('diproses', 'Sedang Diproses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='baru', max_length=15, verbose_name='Status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Catatan Penyelesaian')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Catatan Internal (tidak terlihat pelanggan)')),
                ('sla_deadline', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Batas Waktu SLA')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai pada')),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating Kepuasan (1-5)')),
                ('satisfaction_feedback', models.TextField(blank=True, verbose_name='Masukan Tambahan')),
                ('rated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dinilai pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Ditangani oleh')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.branch', verbose_name='Cabang')),
            ],
            options={
                'verbose_name': 'Komplain',
                'verbose_name_plural': 'Komplain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=15, verbose_name='Status Lama')),
                ('new_status', models.CharField(max_length=15, verbose_name='Status Baru')),
                ('note', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah oleh')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='complaints.complaint', verbose_name='Komplain')),
            ],
            options={
                'verbose_name': 'Riwayat Status',
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff / PIC Cabang'), ('manager', 'Manager Cabang'), ('admin', 'Admin Pusat')], default='staff', max_length=20, verbose_name='Peran')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='No. WhatsApp')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Foto Profil')),
                ('is_active_pic', models.BooleanField(default=True, verbose_name='Aktif Menerima Komplain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('branch', models.ForeignKey(blank=True, help_text='Kosongkan untuk Admin Pusat (akses semua cabang).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='complaints.branch', verbose_name='Cabang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun Pengguna')),
            ],
            options={
                'verbose_name': 'Profil Staff',
                'verbose_name_plural': 'Profil Staff',
            },
        ),
    ]
