# Generated by Django 5.2.17 on 2026-08-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kota')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
            ],
            options={
                'verbose_name': 'Kota',
                'verbose_name_plural': 'Kota',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Isi untuk peran Staff/PIC Cabang (akses 1 cabang spesifik).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='complaints.branch', verbose_name='Cabang'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff / PIC Cabang'), ('input_staff', 'Staff Input Komplain'), ('manager', 'Manager Kota'), ('area_manager', 'Manager Wilayah'), ('admin', 'Admin Pusat')], default='staff', max_length=20, verbose_name='Peran'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Isi untuk peran Manager Kota (akses semua cabang di kota tsb).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='complaints.city', verbose_name='Kota'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='complaints.city', verbose_name='Kota'),
        ),
    ]
