# Generated by Django 5.2.17 on 2026-08-24 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_city_alter_staffprofile_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validasi'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Divalidasi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_validated', to=settings.AUTH_USER_MODEL, verbose_name='Divalidasi oleh'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Solusi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Akar Masalah'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff / PIC Cabang'), ('input_staff', 'Staff Input Komplain'), ('validator', 'Validator'), ('manager', 'Manager Kota'), ('area_manager', 'Manager Wilayah'), ('admin', 'Admin Pusat')], default='staff', max_length=20, verbose_name='Peran'),
        ),
    ]
