# Generated by Django 5.2.17 on 2026-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_validated_complaint_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Diisi Staff/PIC Cabang setelah Solusi diisi, sebelum dikonfirmasi Validator.', verbose_name='Validasi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Dikonfirmasi Validator'),
        ),
    ]
