# Generated by Django 5.2.17 on 2026-08-25 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_validation_notes_alter_complaint_validated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solution_confirmed',
            field=models.BooleanField(default=False, verbose_name='Solusi Dikonfirmasi Validator'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='solution_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solusi dikonfirmasi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='solution_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_solution_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Solusi dikonfirmasi oleh'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Diisi Staff/PIC Cabang setelah Solusi dikonfirmasi Validator.', verbose_name='Validasi'),
        ),
    ]
