# Generated by Django 5.2.17 on 2026-08-27 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_solution_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(choices=[('produk', 'Komplain Produk'), ('servis', 'Komplain Servis')], max_length=10, verbose_name='Jenis Komplain')),
                ('name', models.CharField(max_length=150, verbose_name='Rincian Komplain')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
            ],
            options={
                'verbose_name': 'Rincian Komplain',
                'verbose_name_plural': 'Rincian Komplain',
                'ordering': ['main_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sumber Komplain')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
            ],
            options={
                'verbose_name': 'Sumber Komplain',
                'verbose_name_plural': 'Sumber Komplain',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Outlet', 'verbose_name_plural': 'Outlet'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='cs_handled_time',
            field=models.DateTimeField(blank=True, help_text='Jam saat Staff Input Komplain menginput data komplain ini ke sistem.', null=True, verbose_name='Jam Komplain Ditangani CS'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer_complaint_time',
            field=models.DateTimeField(blank=True, help_text='Jam saat pelanggan menyampaikan komplain (mis. lewat telepon/WA).', null=True, verbose_name='Jam Komplain Masuk'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Contoh: JKT-01, BDG-02', max_length=20, unique=True, verbose_name='Kode Outlet'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_managed', to=settings.AUTH_USER_MODEL, verbose_name='Manager Outlet'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nama Outlet'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.branch', verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('produk', 'Komplain Produk'), ('servis', 'Komplain Servis')], max_length=20, verbose_name='Jenis Komplain'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Diisi Staff/PIC Outlet setelah Solusi dikonfirmasi Validator.', verbose_name='Validasi'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Isi untuk peran Staff/PIC Outlet (akses 1 outlet spesifik).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='complaints.branch', verbose_name='Outlet'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Isi untuk peran Manager Kota (akses semua outlet di kota tsb).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='complaints.city', verbose_name='Kota'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff / PIC Outlet'), ('qc_trainer', 'QC/Trainer'), ('input_staff', 'Staff Input Komplain'), ('validator', 'Validator'), ('manager', 'Manager Kota'), ('area_manager', 'Manager Wilayah'), ('admin', 'Admin Pusat')], default='staff', max_length=20, verbose_name='Peran'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='detail_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.complaintdetailitem', verbose_name='Rincian Komplain'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.complaintsource', verbose_name='Sumber Komplain'),
        ),
    ]
