# Generated by Django 5.2.17 on 2026-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaintdetailitem_complaintsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sla_reminder_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Penanda internal supaya reminder WhatsApp 3 jam sebelum SLA tidak terkirim berulang.', verbose_name='Reminder SLA Terkirim'),
        ),
    ]
