# Generated by Django 5.2.17 on 2026-08-28 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_sla_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='manager_response',
            field=models.TextField(blank=True, verbose_name='Tanggapan MA'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='manager_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggapan diisi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='manager_response_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_manager_response', to=settings.AUTH_USER_MODEL, verbose_name='Tanggapan diisi oleh'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Leader Outlet'), ('qc_trainer', 'QC/Trainer'), ('input_staff', 'CS'), ('validator', 'Validator'), ('manager', 'Manager Area'), ('area_manager', 'Pusat'), ('admin', 'Admin')], default='staff', max_length=20, verbose_name='Peran'),
        ),
    ]
