# Generated by Django 5.2.17 on 2026-08-29 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_manager_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='lo_followup',
            field=models.TextField(blank=True, verbose_name='Tindak Lanjut LO'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lo_followup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tindak lanjut diisi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lo_followup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_lo_followup', to=settings.AUTH_USER_MODEL, verbose_name='Tindak lanjut diisi oleh'),
        ),
    ]
