# Generated by Django 5.2.17 on 2026-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_lo_followup_complaint_lo_followup_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solution_photo',
            field=models.ImageField(blank=True, help_text='Opsional. Foto bukti/pendukung solusi yang diberikan.', null=True, upload_to='solution_photos/%Y/%m/', verbose_name='Foto Solusi'),
        ),
    ]
