# Generated by Django 5.2.17 on 2026-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_solution_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='solution_confirmed',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='solution_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='solution_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='validated_by',
        ),
        migrations.AddField(
            model_name='complaint',
            name='internal_notes_filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solusi diisi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='quality_alert',
            field=models.TextField(blank=True, verbose_name='Quality Alert'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='quality_alert_filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quality Alert diisi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='quality_alert_photo',
            field=models.ImageField(blank=True, help_text='Wajib. Foto bukti terkait Quality Alert.', null=True, upload_to='quality_alert_photos/%Y/%m/', verbose_name='Foto Quality Alert'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes_filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Akar Masalah diisi pada'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='validation_notes_filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validasi diisi pada'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Batas Waktu Deadline'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sla_reminder_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Penanda internal supaya reminder WhatsApp 3 jam sebelum Deadline tidak terkirim berulang.', verbose_name='Reminder Deadline Terkirim'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='solution_photo',
            field=models.ImageField(blank=True, help_text='Wajib. Foto bukti/pendukung solusi yang diberikan.', null=True, upload_to='solution_photos/%Y/%m/', verbose_name='Foto Solusi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Diisi QC/Trainer setelah Akar Masalah, Solusi, dan Quality Alert lengkap terisi.', verbose_name='Validasi'),
        ),
    ]
