# Generated by Django 5.2.17 on 2026-09-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_remove_complaint_solution_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solution_reminder_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Penanda internal supaya reminder WhatsApp (12 jam, Solusi belum diisi) tidak terkirim berulang.', verbose_name='Reminder Solusi Terkirim'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='deadline_hours',
            field=models.PositiveIntegerField(default=48, verbose_name='Deadline (jam)'),
        ),
    ]
