# Generated by Django 5.2.17 on 2026-09-07 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_complaint_solution_reminder_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sheets_backup_sent',
            field=models.BooleanField(default=False, editable=False, help_text='Penanda internal supaya backup ke Google Sheets (saat Deadline lewat) tidak terkirim berulang.', verbose_name='Backup Google Sheets Terkirim'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Leader Outlet'), ('qc_trainer', 'QC/Trainer'), ('qc_office', 'QC Office'), ('input_staff', 'CS'), ('validator', 'Validator'), ('manager', 'Manager Area'), ('area_manager', 'Pusat'), ('admin', 'Admin')], default='staff', max_length=20, verbose_name='Peran'),
        ),
        migrations.CreateModel(
            name='OutletVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_photo', models.ImageField(help_text='Wajib. Foto diambil langsung dari kamera, berisi tanggal, jam, dan lokasi.', upload_to='qc_visit_selfies/%Y/%m/', verbose_name='Foto Selfi')),
                ('order_time', models.DateTimeField(verbose_name='Tgl & Jam Order Makanan (sesuai struk)')),
                ('food_ready_time', models.DateTimeField(verbose_name='Tgl & Jam Makanan Tersedia')),
                ('product_complaint_notes', models.TextField(blank=True, verbose_name='Komplain Produk')),
                ('service_complaint_notes', models.TextField(blank=True, verbose_name='Komplain Servis')),
                ('rating_food_quality', models.PositiveSmallIntegerField(verbose_name='Rating: Kualitas Makanan')),
                ('rating_product_appearance', models.PositiveSmallIntegerField(verbose_name='Rating: Tampilan Produk')),
                ('rating_facility_comfort', models.PositiveSmallIntegerField(verbose_name='Rating: Fasilitas/Kenyamanan')),
                ('rating_cleanliness', models.PositiveSmallIntegerField(verbose_name='Rating: Kebersihan')),
                ('rating_serving_speed', models.PositiveSmallIntegerField(verbose_name='Rating: Kecepatan Penyajian')),
                ('rating_staff_service', models.PositiveSmallIntegerField(verbose_name='Rating: Pelayanan Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_visits', to='complaints.branch', verbose_name='Outlet yang Dikunjungi')),
                ('qc_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_visits', to=settings.AUTH_USER_MODEL, verbose_name='QC Office')),
            ],
            options={
                'verbose_name': 'Kunjungan Outlet (QC Office)',
                'verbose_name_plural': 'Kunjungan Outlet (QC Office)',
                'ordering': ['-created_at'],
            },
        ),
    ]
