# Generated by Django 5.2.17 on 2026-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_complaint_sheets_backup_sent_alter_staffprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletvisit',
            name='employee_name',
            field=models.CharField(blank=True, help_text='Nama karyawan outlet yang dikunjungi/dinilai saat itu.', max_length=150, verbose_name='Nama Karyawan'),
        ),
    ]
