# Generated by Django 5.2.17 on 2026-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_outletvisit_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletvisit',
            name='product_complaint_notes',
        ),
        migrations.RemoveField(
            model_name='outletvisit',
            name='service_complaint_notes',
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Keterangan Tambahan'),
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='cleanliness_notes',
            field=models.TextField(blank=True, verbose_name='Catatan: Kebersihan'),
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='facility_comfort_notes',
            field=models.TextField(blank=True, verbose_name='Catatan: Fasilitas/Kenyamanan'),
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='food_quality_notes',
            field=models.TextField(blank=True, verbose_name='Catatan: Kualitas Makanan'),
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='product_appearance_notes',
            field=models.TextField(blank=True, verbose_name='Catatan: Tampilan Produk'),
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='serving_speed_notes',
            field=models.TextField(blank=True, verbose_name='Catatan: Kecepatan Penyajian'),
        ),
        migrations.AddField(
            model_name='outletvisit',
            name='staff_service_notes',
            field=models.TextField(blank=True, verbose_name='Catatan: Keramahan Kasir/Staff (5S)'),
        ),
        migrations.AlterField(
            model_name='outletvisit',
            name='rating_staff_service',
            field=models.PositiveSmallIntegerField(verbose_name='Rating: Keramahan Kasir/Staff (5S)'),
        ),
    ]
