# Generated by Django 5.2.17 on 2026-09-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_remove_outletvisit_product_complaint_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, help_text='Format: xxxxxxxxxxxxx@g.us (lihat cara mendapatkannya di dokumentasi Fonnte). Kosongkan kalau kota ini belum punya grup -- laporan kunjungan QC tidak akan dikirim ke grup mana pun untuk kota ini.', max_length=100, verbose_name='ID Grup WhatsApp QC Report'),
        ),
    ]
