# Generated by Django 5.2.17 on 2026-09-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_city_whatsapp_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Leader Outlet'), ('qc_trainer', 'QC/Trainer'), ('qc_office', 'QC Office'), ('input_staff', 'CS'), ('validator', 'Validator'), ('manager', 'Manager Area'), ('area_manager', 'Pusat'), ('hc', 'HC'), ('admin', 'Admin')], default='staff', max_length=20, verbose_name='Peran'),
        ),
    ]
